steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/munchies-api/lunar-ensign-287519:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/munchies-api/lunar-ensign-287519:$SHORT_SHA']
