steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lunar-ensign-287519/munchies-be:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lunar-ensign-287519/munchies-be:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'lunar-ensign-287519', '--region=europe-west1', '--platform=managed', '--image=gcr.io/lunar-ensign-287519/munchies-be:$SHORT_SHA']
